wandb_version: 1

batch_size:
  desc: null
  value: 29
learning_rate:
  desc: null
  value: 0.007059217397209685
num_epochs:
  desc: null
  value: 25
optimizer:
  desc: null
  value: Adam
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697071386.473687
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.9.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
